image: muhifauzan/alpine-elixir:1.5.0

stages:
  - build
  - static-analysis
  - test
  - publish

variables:
  MIX_ENV: test
  REPO: muhifauzan/guard-gen

cache:
  paths:
    - _build
    - deps

build:
  stage: build
  script:
    - mix deps.get
    - mix compile --force --warnings-as-errors

dialyzer:
  stage: static-analysis
  script:
    - mix dialyzer --halt-exit-status
  except:
    - tags

credo:
  stage: static-analysis
  script:
    - mix credo
  except:
    - tags

test:
  stage: test
  script:
    - mix test
  except:
    - tags

hex:
  stage: publish
  script:
    - mix hex.config username $HEX_USERNAME
    - mix hex.config encrypted_key $HEX_ENCRYPTED_KEY > /dev/null 2>&1
    - mix hex.build
    - echo ${HEX_PASSPHRASE}$'\n'Y | mix hex.publish
  environment:
    name: hex
    url: https://hex.pm/packages/guard_gen/${CI_COMMIT_TAG#"v"}
  only:
    - tags

inch:
  stage: publish
  script:
    - git checkout master
    - git remote set-url origin https://github.com/${REPO}.git
    - mix inch.report
  environment:
    name: inch
    url: https://inch-ci.org/github/${REPO}
  only:
    - master
